const mongoose = require("mongoose");
const userLoginDataSchema = new mongoose.Schema(
    {
        email: { type: String, require: true, unique: true },
        password: { type: String},
        loginFrom: { type: String, enum: ["web", "google","facebook", "github", "linkedin"]},
        id: { type: String },
        username: { type: String },
        name: { type: String },
        firstName: { type: String },
        lastName: { type: String },
        mobileNumber: { type: Number },
        gender: { type: String, enum: ["Male", "Female","male", "female"] },
        location: { type: String },
        hometown_id: { type: String },
        hometown_name: { type: String },
        birthday: { type: Date },
        porfilePicture: { type: String },
        likes: { type: Array },
        friends: { type: Number },
        verifiedEmail: { type: Boolean },
        isGuestUser: { type: Boolean },
        locale: { type: String },
        posts: { type: Array },
        avatar_url: { type: String },
        bio: { type: String },
        created_at: { type: String },
        events_url: { type: String },
        followers: { type: Number },
        followers_url: { type: String },
        following: { type: Number },
        following_url: { type: String },
        gists_url: { type: String },
        updated_at: { type: String },
        organizations_url: { type: String },
        public_repos: { type: Number },
        received_events_url: { type: String },
        repos_url: { type: String },
        site_admin: { type: Boolean },
        subscriptions_url: { type: String },
        twitter_username: { type: String },
        type: { type: String },
        blog: { type: String },
        profile_url: { type: String },
        github_primary: { type: Boolean },
        github_visibility: { type: String, enum: ["private", "public"]},
    },
    {
        timestamps: true,
    }
);

const userLoginDataModel = mongoose.model("user_login", userLoginDataSchema);
module.exports = userLoginDataModel;
